/*******************************************************************************
Project Name    : general (part of the p21spec_creator package)
Program Name    : p21spec_create_sheet_meta.sas
Program Author  : Thomas Gulholm-Hansen (TGUH)
Program Purpose : Create the dataset defdata.spec_sheet_meta containing the 
                  sheets and variables to be written to the upload-file.
Parameters:
  col_list      : (space separated) List of macro variables holding the 'column
                  definition'-data. Variabes are define in the driver program
                  for easier updates.
*******************************************************************************/

* Create dataset base on the specified 'column variable macro variables';

%macro p21spec_create_sheet_meta(
  col_list = col_Define col_Datasets col_Variables col_ValueLevel col_Codelists col_Dictionaries col_Methods col_Comments col_Documents
);

data sheet_meta;
  length sheet $50 sheetn order 8 label note $200 read_ignore write_ignore in_spec in_data 8;
  length col_list_id _column_item $200 col_list_val $2000 i j 8;
  keep sheet--in_data;

  * Initiate IN_SPEC and IN_DATA (they are expected by the excel_import module ;
  in_spec=.n;
  in_data=.n;

  do i=1 to countw("&col_list");
    col_list_id = scan("&col_list.",i);
    col_list_val = symget(col_list_id);
    sheet = scan(col_list_id,2,'_');

    do j=1 to count(col_list_val,',')+1;
      _column_item = strip(compress(scan(col_list_val,j,','),"'"));
      sheetn=i;
      order = (sheetn*100)+j;

      * Checke the specified 'columns' for control characters and set label, ignore-variables and note accordingly;
      if substr(_column_item,1,1) eq '*' then do;
        label=substr(_column_item,2);
        read_ignore = 1;
        note = 'Variable will be generated by the P21SpecCreator, so not included/read from the entry-file';
      end;
     if substr(_column_item,1,1) eq '-' then do;
        label=substr(_column_item,2);
        write_ignore = 1;
        note = 'Control variable in the entry-file, not to be written to the P21UploadSpec';
      end;


      if missing(label) then label=_column_item;
      output;

      call missing(label, note, read_ignore, write_ignore);
    end;
  end;
run;

proc sort data=sheet_meta out=defdata.spec_sheet_meta;
  by order sheetn order;
run;

proc datasets lib=work nolist;
  delete sheet_meta;
quit;

%mend;
