/*******************************************************************************
Project Name    : general (part of the p21spec_creator package)
Program Name    : p21spec_define.sas
Program Author  : Thomas Gulholm-Hansen (TGUH)
Program Purpose : Get "global variables", e.g., standard versions and run-
                  configuration from the define sheet and store them as 
                  global and read-only macro variables.
                  Write a new define sheet-dataset, including notes that the 
                  upload-file is note intended to be updated manually
Parameters:
*******************************************************************************/

%macro p21spec_define(
  inds_define = &_LASTDS_DEFINE.,
  outds_define = temp_define_updated
);

*******************************************************************************;
* Modify define-sheet to inform not to update the autogenerated file;
*******************************************************************************;
data &outds_define.;
  format value $2000.;
  informat value $2000.;
  length value $2000;

  set defdata.Entry_define end=eof;
  length _mvar_name $32 _mvar_value $200;

  * Prepare default versoins for storing as gloabl macro variables ;
  if upcase(attribute) eq 'DEFAULT DATASETS STANDARD' then do;
    _mvar_name = '_DEFAULT_DATASETS_STANDARD';
    _mvar_value = value;
  end;
  if upcase(attribute) eq 'DEFAULT CODELISTS TERMINOLOGY' then do;
    _mvar_name = '_DEFAULT_CODELISTS_TERMINOLOGY';
    _mvar_value = value;
  end;

  * Prepare run-configurations for storing as global macro variables;
  if upcase(strip(scan(attribute,1,':'))) eq 'RUNCONFIG' then do;
    _mvar_name = '_' || tranwrd(compbl(upcase(strip(scan(attribute,2,':')))),' ','_');
    _mvar_value = ifc(upcase(value) in ('ON', '1'), 'ON', 'OFF');
  end;

  * Delete 'Legen rows' (not applicable for the upload-file); 
  if not (attribute eq 'Legend' or (missing(attribute) and not missing(value))) then output; 

  * store global macro variables derived above ;
  if not missing(_mvar_name) then do;
    call execute('%global /readonly ' || strip(_mvar_name) || ' = ' || strip(_mvar_value));
  end;
 
  * Write 'upload file specific' usage notes ;
  if eof then do;
    attribute = '';
    value = '';
    output;
    attribute = 'UsageNote';
    value = 'This workbook is autogenerated by the make_p21_spec-tool, for upload to Pinnacle 21 - DO NOT update it directly';
    output;
    attribute = 'UsageNote';
    value = 'Instead, update the EntryFile specified below and re-run make_p21_spec.sas';
    output;
    attribute = 'EntryFile';
    value = "&entryfile_path.";
    output;
    attribute = 'Created';
    value = "&sysdate. &systime.";
    output;
  end;
run;

* Update Gloable DS-name variable;
%let _LASTDS_DEFINE = &outds_define.;

%mend;
