/*******************************************************************************
  Bundle: p21spec_create_sheet_meta

  Exercises the p21spec_creator macro %p21spec_create_sheet_meta against the
  exact column specifications the driver (p21spec_creator.sas) declares. The
  macro turns the col_* macro variables into the defdata.spec_sheet_meta
  control dataset, honouring the leading '*' (generated, read-ignore) and '-'
  (control, write-ignore) prefixes on column labels.

  The %let col_* blocks below are copied from the ADaM driver; the macro body
  is copied verbatim from macro/p21spec_create_sheet_meta.sas.
*******************************************************************************/

/* --- Column specifications, copied from p21spec_creator.sas (ADaM) --- */
%let col_Define       = 'Attribute', 'Value';
%let col_Datasets     = 'Dataset', 'Label', 'Class', 'SubClass', 'Structure', 'Key Variables', 'Standard', 'Has No Data', 'Repeating', 'Reference Data', 'Comment', 'Developer Notes';
%let col_Variables    = 'Order', 'Dataset', 'Variable', 'Label', 'Data Type', 'Length', 'Significant Digits', 'Format', 'Mandatory', 'Assigned Value', 'Codelist', 'Common', 'Origin', 'Source', 'Pages', 'Method', '-Method Expression Context',  '-Method Expression Code', '-Method Document', '-Method Pages', 'Predecessor', 'Role', 'Has No Data', 'Comment', '-Comment Document', '-Comment Pages', 'Developer Notes', '-Core Group', '*_core_variable_note';
%let col_ValueLevel   = 'Order', 'Dataset', 'Variable', 'Where Clause', 'Label', 'Data Type', 'Length', 'Significant Digits', 'Format', 'Mandatory', 'Assigned Value', 'Codelist', 'Origin', 'Source', 'Pages', 'Method', '-Method Expression Context',  '-Method Expression Code', '-Method Document', '-Method Pages', 'Predecessor', 'Comment', '-Comment Document', '-Comment Pages', 'Developer Notes', 'Qeval';
%let col_Codelists    = 'ID', 'Name', 'NCI Codelist Code', 'Data Type', 'Terminology', 'Comment', 'Order', 'Term', 'NCI Term Code', 'Decoded Value';
%let col_Dictionaries = 'ID', 'Name', 'Data Type', 'Dictionary', 'Version';
%let col_Methods      = 'ID', 'Name', 'Type', 'Description', 'Expression Context', 'Expression Code', 'Document', 'Pages';
%let col_Comments     = 'ID', 'Description', 'Document', 'Pages';
%let col_Documents    = 'ID', 'Title', 'Href';

/* --- Macro body, copied verbatim from macro/p21spec_create_sheet_meta.sas --- */
%macro p21spec_create_sheet_meta(
  col_list = col_Define col_Datasets col_Variables col_ValueLevel col_Codelists col_Dictionaries col_Methods col_Comments col_Documents
);

data sheet_meta;
  length sheet $50 sheetn order 8 label note $200 read_ignore write_ignore in_spec in_data 8;
  length col_list_id _column_item $200 col_list_val $2000 i j 8;
  keep sheet--in_data;

  * Initiate IN_SPEC and IN_DATA (they are expected by the excel_import module ;
  in_spec=.n;
  in_data=.n;

  do i=1 to countw("&col_list");
    col_list_id = scan("&col_list.",i);
    col_list_val = symget(col_list_id);
    sheet = scan(col_list_id,2,'_');

    do j=1 to count(col_list_val,',')+1;
      _column_item = strip(compress(scan(col_list_val,j,','),"'"));
      sheetn=i;
      order = (sheetn*100)+j;

      * Checke the specified 'columns' for control characters and set label, ignore-variables and note accordingly;
      if substr(_column_item,1,1) eq '*' then do;
        label=substr(_column_item,2);
        read_ignore = 1;
        note = 'Variable will be generated by the P21SpecCreator, so not included/read from the entry-file';
      end;
     if substr(_column_item,1,1) eq '-' then do;
        label=substr(_column_item,2);
        write_ignore = 1;
        note = 'Control variable in the entry-file, not to be written to the P21UploadSpec';
      end;


      if missing(label) then label=_column_item;
      output;

      call missing(label, note, read_ignore, write_ignore);
    end;
  end;
run;

proc sort data=sheet_meta out=defdata.spec_sheet_meta;
  by order sheetn order;
run;

proc datasets lib=work nolist;
  delete sheet_meta;
quit;

%mend;

/* --- Build the control dataset and show what it produced --- */
%p21spec_create_sheet_meta;

proc print data=defdata.spec_sheet_meta;
  var sheet sheetn order label read_ignore write_ignore;
run;
